apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque               # Important as this one make Encodebase64
data:
  username: YWRtaW4=       # base64 of 'admin'
  password: cGFzc3dvcmQ=   # base64 of 'password'



# env: 
#    valueFrom:
#       secretRef: 
#          name: app-secret
#          key: DB_USER 

# envFrom:
#    - secretRef:
#        name: app-secret # this will enject all value
      

# volumes: 
#    -  name : secret-vol
#       secret:
#          secretname: app-secret

# volumemount:
#    -  name: secret-vol 
#       mountPath: /etc/secret
#       readOnly: true