apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque               # Important as this one make Encodebase64
data:
  username: YWRtaW4=       # base64 of 'admin'
  password: cGFzc3dvcmQ=   # base64 of 'password'
