### To use the Autoscaling you need a deployment first. First make deployment then apply Autoscaling
### Learn Bottelneck -cpu , memory 
### Load-gentrater to test the system


apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: my-app
  updatePolicy:
    updateMode: "Auto"   # Options: "Off" | "Initial" | "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: my-app-container
        minAllowed:
          cpu: "100m"
          memory: "128Mi"
        maxAllowed:
          cpu: "1000m"
          memory: "1Gi"
        controlledResources: ["cpu", "memory"]
