apiVersion: v1 
kind: NameSpace 
metadata:
    name: dv
    labels:
       apps: nginx 
       env: production
    annotation:
       description: "Hello World"
       owner:
spec:         ### optional
  finalizers:
     - kubernetes