# ✅ 4️⃣ Default NetworkPolicy (Zero Trust – Mandatory)

# 📌 This is CRITICAL in production
# By default → NO pod can talk to anything
# You must explicitly allow traffic
# Interview keyword: “Zero Trust Networking”


## Default Deny All Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: dev
spec:
  podSelector: {}                  ## Applies to all Pods
  policyTypes:
  - Ingress                        ## Block all incoming traffic
  - Egress                         ## Block all outgoing traffic



...
## ✅ (Optional but REAL) Allow DNS Access

# -------------------------------------
# NetworkPolicy (Allow DNS)
# -------------------------------------
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: production
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53


